// auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const EXTEND_TOKEN_SUCCESS = 'EXTEND_TOKEN_SUCCESS';
export const EXTEND_TOKEN_FAIL = 'EXTEND_TOKEN_FAIL';

// alerts
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// appliances
export const GET_APPLIANCES_SUCCESS = 'GET_APPLIANCES';
export const GET_APPLIANCES_FAIL = 'GET_APPLIANCES_FAIL';
export const ADD_APPLIANCE_SUCCESS = 'ADD_APPLIANCE_SUCCESS';
export const ADD_APPLIANCE_FAIL = 'ADD_APPLIANCE_FAIL';
export const TOGGLE_APPLIANCE_FORM = 'TOGGLE_APPLIANCE_FORM';
