# Generated by Django 3.1.1 on 2020-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
