# Generated by Django 3.1.1 on 2020-11-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_auto_20201126_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
