# Generated by Django 3.1.1 on 2020-11-26 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_appliance_description'),
        ('accessories', '0004_accessory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='appliances.appliance'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='serial_number',
            field=models.CharField(blank=True, error_messages={'unique': 'An appliance already exists with that serial number'}, max_length=50, null=True),
        ),
    ]
