# Generated by Django 3.1.1 on 2020-11-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_appliance_description'),
        ('accessories', '0005_auto_20201126_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance'),
        ),
    ]
