# Generated by Django 3.1.1 on 2020-11-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0008_auto_20201126_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='appliance',
        ),
    ]
