# Generated by Django 3.1.1 on 2020-11-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_appliance_description'),
        ('accessories', '0009_remove_accessory_appliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={},
        ),
        migrations.AddField(
            model_name='accessory',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='appliances.appliance'),
        ),
    ]
