# Generated by Django 3.1.1 on 2020-10-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201016_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username has already been registered.'}, max_length=20, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
