# Generated by Django 3.1.1 on 2020-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username has already been registered.'}, max_length=20, null=True, unique=True, verbose_name='username'),
        ),
    ]
