# Generated by Django 3.1.1 on 2020-10-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201020_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username has already been registered.'}, max_length=20, unique=True, verbose_name='username'),
        ),
    ]
