# Generated by Django 3.1 on 2020-08-27 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_serviced', models.DateTimeField(blank=True, null=True)),
                ('manual_url', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
