# Generated by Django 3.1.1 on 2020-10-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='appliance_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliance',
            name='model_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
