# Generated by Django 3.1.1 on 2020-10-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='category',
            field=models.ManyToManyField(to='categories.Category'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
