# Generated by Django 3.1.1 on 2020-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_auto_20201021_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(blank=True, error_messages={'unique': 'An appliance already exists with that serial number'}, max_length=50, unique=True),
        ),
    ]
