# Generated by Django 3.1.1 on 2020-10-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_auto_20201024_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
