# Generated by Django 3.1.1 on 2020-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_appliance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
